title: ### Iuliana Georgescu - Computer Vision Researcher
description: I am a final-year Ph.D. candidate in the Computer Science department at University of Bucharest. I am very happy to be advised by Prof. Dr. Radu Ionescu. I previously worked on video anomaly detection and medical image analysis. My current research interst is self-supervision and multi-modal learning.
theme: jekyll-theme-cayman
