title: Iuliana Georgescu
description: I am a final-year Ph.D. candidate in Computer Vision at University of Bucharest. I am very happy to be advised by Prof. Dr. Radu Ionescu. I previously worked on video anomaly detection and medical image analysis. My current research intersts are self-supervision and multi-modal learning.
theme: jekyll-theme-cayman
